# Generated by Django 5.0.1 on 2024-08-26 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='Posts',
        ),
    ]
