# Generated by Django 5.0.1 on 2024-01-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='email',
            field=models.EmailField(error_messages={'already_taken': 'This email is already taken!'}, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='username',
            field=models.CharField(error_messages={'already_taken': 'This username is already taken!'}, max_length=255, unique=True),
        ),
    ]
