# Generated by Django 5.0.1 on 2024-10-09 17:00

import auth_user.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0002_alter_authuser_email_alter_authuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='password',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(8, 'Password must contain at least 8 symbols!'), auth_user.validators.validate_password_for_strength]),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='username',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(4, 'Username must contain at least 4 symbols!'), auth_user.validators.validate_username_for_forbidden_symbols]),
        ),
    ]
